# Generated by Django 2.2.14 on 2023-06-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='song_artist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='song_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
